// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceHunt.Api.Data;

#nullable disable

namespace PriceHunt.Api.Data.Migrations
{
    [DbContext(typeof(PriceHuntDbContext))]
    [Migration("20261005235323_PriceToCents")]
    partial class PriceToCents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PriceHunt.Api.Domain.SearchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("PriceHunt.Api.Domain.SearchSupplier", b =>
                {
                    b.Property<Guid>("SearchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SearchId", "Supplier");

                    b.HasIndex("Supplier");

                    b.ToTable("SearchSuppliers");
                });

            modelBuilder.Entity("PriceHunt.Api.Domain.SupplierResponseRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchId");

                    b.HasIndex("Supplier");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("PriceHunt.Api.Domain.SearchSupplier", b =>
                {
                    b.HasOne("PriceHunt.Api.Domain.SearchRecord", "Search")
                        .WithMany("SelectedSuppliers")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Search");
                });

            modelBuilder.Entity("PriceHunt.Api.Domain.SupplierResponseRecord", b =>
                {
                    b.HasOne("PriceHunt.Api.Domain.SearchRecord", "Search")
                        .WithMany("Responses")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Search");
                });

            modelBuilder.Entity("PriceHunt.Api.Domain.SearchRecord", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("SelectedSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
